# -------------------------------------
# Script: get_hillary
# Author: Anton Hung
# Purpose: modification of 06_define_OUD_components/define_oud_hillary.R
#          This script finds and saves all hillary OUD dates, not just the first one
# Notes:
# -------------------------------------


# load libraries
library(arrow)
library(tidyverse)
library(tidylog)
library(lubridate)
library(data.table)
library(furrr)


surgeries <- readRDS("/mnt/general-data/disability/post_surgery_opioid_use/intermediate/surgery_claims.rds")

# otl and rxl data for finding opioid claims
src_root <- "/mnt/processed-data/disability"

# Read in OTL (Other services line) 
files <- paste0(list.files(src_root, pattern = "TAFIPH", recursive = TRUE))
parquet_files <- grep("\\.parquet$", files, value = TRUE)
iph <- open_dataset(file.path(src_root, parquet_files))

# Read in RXL (pharmacy line)
files <- paste0(list.files(src_root, pattern = "TAFOTH", recursive = TRUE))
parquet_files <- grep("\\.parquet$", files, value = TRUE)
oth <- open_dataset(file.path(src_root, parquet_files))

hillary_codes_abuse <-
  c(
    "F11",      #  OPIOID RELATED DISORDERS
    "F111",     # OPIOID ABUSE
    "F1110",    # OPIOID ABUSE, UNCOMPLICATED
    "F1110",    # OPIOID ABUSE, UNCOMPLICATED
    "F1111",    # OPIOID ABUSE, IN REMISSION
    "F1112",    # OPIOID ABUSE WITH INTOXICATION
    "F11120",   # OPIOID ABUSE WITH INTOXICATION, UNCOMPLICATED
    "F11120",   # OPIOID ABUSE WITH INTOXICATION, UNCOMPLICATED
    "F11121",   # OPIOID ABUSE WITH INTOXICATION DELIRIUM
    "F11121",   # OPIOID ABUSE WITH INTOXICATION DELIRIUM
    "F11122",   # OPIOID ABUSE WITH INTOXICATION WITH PERCEPTUAL DISTURBANCE
    "F11122",   # OPIOID ABUSE WITH INTOXICATION WITH PERCEPTUAL DISTURBANCE
    "F11129",   # OPIOID ABUSE WITH INTOXICATION, UNSPECIFIED
    "F11129",   # OPIOID ABUSE WITH INTOXICATION, UNSPECIFIED
    "F1114",    # OPIOID ABUSE WITH OPIOID-INDUCED MOOD DISORDER
    "F1114",    # OPIOID ABUSE WITH OPIOID-INDUCED MOOD DISORDER
    "F1115",    # OPIOID ABUSE WITH OPIOID-INDUCED PSYCHOTIC DISORDER
    "F11150",   # OPIOID ABUSE W OPIOID-INDUCED PSYCHOTIC DISORDER W DELUSIONS
    "F11150",   # OPIOID ABUSE W OPIOID-INDUCED PSYCHOTIC DISORDER W DELUSIONS
    "F11151",   # OPIOID ABUSE W OPIOID-INDUCED PSYCHOTIC DISORDER W HALLUCIN
    "F11151",   # OPIOID ABUSE W OPIOID-INDUCED PSYCHOTIC DISORDER W HALLUCIN
    "F11159",   # OPIOID ABUSE WITH OPIOID-INDUCED PSYCHOTIC DISORDER, UNSP
    "F11159",   # OPIOID ABUSE WITH OPIOID-INDUCED PSYCHOTIC DISORDER, UNSP
    "F1118",    # OPIOID ABUSE WITH OTHER OPIOID-INDUCED DISORDER
    "F11181",   # OPIOID ABUSE WITH OPIOID-INDUCED SEXUAL DYSFUNCTION
    "F11181",   # OPIOID ABUSE WITH OPIOID-INDUCED SEXUAL DYSFUNCTION
    "F11182",   # OPIOID ABUSE WITH OPIOID-INDUCED SLEEP DISORDER
    "F11182",   # OPIOID ABUSE WITH OPIOID-INDUCED SLEEP DISORDER
    "F11188",   # OPIOID ABUSE WITH OTHER OPIOID-INDUCED DISORDER
    "F11188",   # OPIOID ABUSE WITH OTHER OPIOID-INDUCED DISORDER
    "F1119",    # OPIOID ABUSE WITH UNSPECIFIED OPIOID-INDUCED DISORDER
    "F1119",    # OPIOID ABUSE WITH UNSPECIFIED OPIOID-INDUCED DISORDER
    "F112",     # OPIOID DEPENDENCE
    "F1120",    # OPIOID DEPENDENCE, UNCOMPLICATED
    "F1120",    # OPIOID DEPENDENCE, UNCOMPLICATED
    "F1121",    # OPIOID DEPENDENCE, IN REMISSION
    "F1121",    # OPIOID DEPENDENCE, IN REMISSION
    "F1122",    # OPIOID DEPENDENCE WITH INTOXICATION
    "F11220",   # OPIOID DEPENDENCE WITH INTOXICATION, UNCOMPLICATED
    "F11220",   # OPIOID DEPENDENCE WITH INTOXICATION, UNCOMPLICATED
    "F11221",   # OPIOID DEPENDENCE WITH INTOXICATION DELIRIUM
    "F11221",   # OPIOID DEPENDENCE WITH INTOXICATION DELIRIUM
    "F11222",   # OPIOID DEPENDENCE W INTOXICATION WITH PERCEPTUAL DISTURBANCE
    "F11222",   # OPIOID DEPENDENCE W INTOXICATION WITH PERCEPTUAL DISTURBANCE
    "F11229",   # OPIOID DEPENDENCE WITH INTOXICATION, UNSPECIFIED
    "F11229",   # OPIOID DEPENDENCE WITH INTOXICATION, UNSPECIFIED
    "F1123",    # OPIOID DEPENDENCE WITH WITHDRAWAL
    "F1123",    # OPIOID DEPENDENCE WITH WITHDRAWAL
    "F1124",    # OPIOID DEPENDENCE WITH OPIOID-INDUCED MOOD DISORDER
    "F1124",    # OPIOID DEPENDENCE WITH OPIOID-INDUCED MOOD DISORDER
    "F1125",    # OPIOID DEPENDENCE WITH OPIOID-INDUCED PSYCHOTIC DISORDER
    "F11250",   # OPIOID DEPEND W OPIOID-INDUC PSYCHOTIC DISORDER W DELUSIONS
    "F11250",   # OPIOID DEPEND W OPIOID-INDUC PSYCHOTIC DISORDER W DELUSIONS
    "F11251",   # OPIOID DEPEND W OPIOID-INDUC PSYCHOTIC DISORDER W HALLUCIN
    "F11251",   # OPIOID DEPEND W OPIOID-INDUC PSYCHOTIC DISORDER W HALLUCIN
    "F11259",   # OPIOID DEPENDENCE W OPIOID-INDUCED PSYCHOTIC DISORDER, UNSP
    "F11259",   # OPIOID DEPENDENCE W OPIOID-INDUCED PSYCHOTIC DISORDER, UNSP
    "F1128",    # OPIOID DEPENDENCE WITH OTHER OPIOID-INDUCED DISORDER
    "F11281",   # OPIOID DEPENDENCE WITH OPIOID-INDUCED SEXUAL DYSFUNCTION
    "F11281",   # OPIOID DEPENDENCE WITH OPIOID-INDUCED SEXUAL DYSFUNCTION
    "F11282",   # OPIOID DEPENDENCE WITH OPIOID-INDUCED SLEEP DISORDER
    "F11282",   # OPIOID DEPENDENCE WITH OPIOID-INDUCED SLEEP DISORDER
    "F11288",   # OPIOID DEPENDENCE WITH OTHER OPIOID-INDUCED DISORDER
    "F11288",   # OPIOID DEPENDENCE WITH OTHER OPIOID-INDUCED DISORDER
    "F1129",    # OPIOID DEPENDENCE WITH UNSPECIFIED OPIOID-INDUCED DISORDER
    "F1129",    # OPIOID DEPENDENCE WITH UNSPECIFIED OPIOID-INDUCED DISORDER
    "F119",     # OPIOID USE, UNSPECIFIED
    "F1190",    # OPIOID USE, UNSPECIFIED, UNCOMPLICATED
    "F1190",    # OPIOID USE, UNSPECIFIED, UNCOMPLICATED
    "F1192",    # OPIOID USE, UNSPECIFIED WITH INTOXICATION
    "F11920",   # OPIOID USE, UNSPECIFIED WITH INTOXICATION, UNCOMPLICATED
    "F11920",   # OPIOID USE, UNSPECIFIED WITH INTOXICATION, UNCOMPLICATED
    "F11921",   # OPIOID USE, UNSPECIFIED WITH INTOXICATION DELIRIUM
    "F11921",   # OPIOID USE, UNSPECIFIED WITH INTOXICATION DELIRIUM
    "F11922",   # OPIOID USE, UNSP W INTOXICATION WITH PERCEPTUAL DISTURBANCE
    "F11922",   # OPIOID USE, UNSP W INTOXICATION WITH PERCEPTUAL DISTURBANCE
    "F11929",   # OPIOID USE, UNSPECIFIED WITH INTOXICATION, UNSPECIFIED
    "F11929",   # OPIOID USE, UNSPECIFIED WITH INTOXICATION, UNSPECIFIED
    "F1193",    # OPIOID USE, UNSPECIFIED WITH WITHDRAWAL
    "F1193",    # OPIOID USE, UNSPECIFIED WITH WITHDRAWAL
    "F1194",    # OPIOID USE, UNSPECIFIED WITH OPIOID-INDUCED MOOD DISORDER
    "F1194",    # OPIOID USE, UNSPECIFIED WITH OPIOID-INDUCED MOOD DISORDER
    "F1195",    # OPIOID USE, UNSP WITH OPIOID-INDUCED PSYCHOTIC DISORDER
    "F11950",   # OPIOID USE, UNSP W OPIOID-INDUC PSYCH DISORDER W DELUSIONS
    "F11950",   # OPIOID USE, UNSP W OPIOID-INDUC PSYCH DISORDER W DELUSIONS
    "F11951",   # OPIOID USE, UNSP W OPIOID-INDUC PSYCH DISORDER W HALLUCIN
    "F11951",   # OPIOID USE, UNSP W OPIOID-INDUC PSYCH DISORDER W HALLUCIN
    "F11959",   # OPIOID USE, UNSP W OPIOID-INDUCED PSYCHOTIC DISORDER, UNSP
    "F11959",   # OPIOID USE, UNSP W OPIOID-INDUCED PSYCHOTIC DISORDER, UNSP
    "F1198",    # OPIOID USE, UNSPECIFIED WITH OTH OPIOID-INDUCED DISORDER
    "F11981",   # OPIOID USE, UNSP WITH OPIOID-INDUCED SEXUAL DYSFUNCTION
    "F11981",   # OPIOID USE, UNSP WITH OPIOID-INDUCED SEXUAL DYSFUNCTION
    "F11982",   # OPIOID USE, UNSPECIFIED WITH OPIOID-INDUCED SLEEP DISORDER
    "F11982",   # OPIOID USE, UNdSPECIFIED WITH OPIOID-INDUCED SLEEP DISORDER
    "F11988",   # OPIOID USE, UNSPECIFIED WITH OTHER OPIOID-INDUCED DISORDER
    "F11988",   # OPIOID USE, UNSPECIFIED WITH OTHER OPIOID-INDUCED DISORDER
    "F1199",    # OPIOID USE, UNSP WITH UNSPECIFIED OPIOID-INDUCED DISORDER
    "F1199"    # OPIOID USE, UNSP WITH UNSPECIFIED OPIOID-INDUCED DISORDER
  )



# Filter arrow files by cohort ---------------------------------------------------------

oth_cohort <- # first extract the other services data
  oth |>
  filter(!is.na(DGNS_CD_1)) |>
  filter(BENE_ID %in% surgeries$BENE_ID) |> 
  mutate(SRVC_BGN_DT = case_when(is.na(SRVC_BGN_DT) ~ SRVC_END_DT, TRUE ~ SRVC_BGN_DT)) |>
  filter(SRVC_BGN_DT >= as.Date("2016-01-01")) |> # save space, keep only DG codes after 2016
  select(BENE_ID, SRVC_BGN_DT,  SRVC_END_DT, contains("DGNS_CD")) |>
  collect()

iph_cohort <- # then extract IPH data
  iph |>
  filter(BENE_ID %in% surgeries$BENE_ID) |> 
  mutate(SRVC_BGN_DT = case_when(is.na(SRVC_BGN_DT) ~ SRVC_END_DT, TRUE ~ SRVC_BGN_DT)) |>
  filter(SRVC_BGN_DT >= as.Date("2016-01-01")) |> # save space, keep only DG codes after 2016
  select(BENE_ID, ADMSN_DT, SRVC_BGN_DT, contains("DGNS_CD")) |>
  collect()



# Create OUD component date variables from IPH and OTH ---------------------------------------------------------


oth_all_vars <-
  oth_cohort |> # define oud variable of interest via codes
  mutate(oud_hillary_dt = case_when(DGNS_CD_1 %in% hillary_codes_abuse ~ SRVC_BGN_DT,
                                   DGNS_CD_2 %in% hillary_codes_abuse ~ SRVC_BGN_DT)) |>
  drop_na(oud_hillary_dt) |> # drop anyone who doesn't have a date for the oud var of interest
  distinct(BENE_ID, oud_hillary_dt)

iph_all_vars <-
  iph_cohort |> # for IPH, first need to pivot to long format because there are 12 DG codes
  pivot_longer(cols = contains("DGNS_CD"), names_to = "dg_num", values_to = "cd") |> # switch to long format data because there are 12 dx codes and IPH isn't too big
  drop_na(cd) |> # drop any missing icd code (cd) rows
  mutate(oud_hillary_dt = case_when(cd %in% hillary_codes_abuse ~ SRVC_BGN_DT)) |>  # define oud variable of interest via codes
  drop_na(oud_hillary_dt) |> # drop anyone who doesn't have a date for the oud var of interest
  distinct(BENE_ID, oud_hillary_dt)

all <- bind_rows(oth_all_vars, iph_all_vars) # stack the columns (BENE_ID and oud var of interest) on top of each other



saveRDS(all, "/mnt/general-data/disability/post_surgery_opioid_use/intermediate/all_hillary_dts.rds")
